version: 0.2

phases:
  install:
    commands:
      # Upgrade AWS CLI to the latest version
      - pip install --upgrade awscli
  pre_build:
    commands:
      - echo Test started on `date`
      - npm install --global gulp
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - gulp
      - mkdir result
      - mv ./dist/lambda.zip ./result
      - mv ./template.yml ./result
      - cd ./result
      - unzip lambda.zip
      - rm -rf lambda.zip
      - aws cloudformation package --template template.yml --s3-bucket nodejs-build-jar --output-template template-export.yml
      - mv template-export.yml ../
artifacts:
  files:
    - template-export.yml
